// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    [Serializable]
    public class MAOWhiteBalanceClip : PlayableAsset, ITimelineClipAsset
    {
        [Range(-100f, 100f)] public float temperature = 4.6f;
        [Range(-100f, 100f)] public float tint = 0f;


        public ClipCaps clipCaps
        {
            get { return ClipCaps.Blending; }
        }

        public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
        {
            var playable = ScriptPlayable<MAOWhiteBalanceBehaviour>.Create(graph);
            var behaviour = playable.GetBehaviour();

            behaviour.Temperature = temperature;
            behaviour.Tint = tint;


            return playable;
        }
    }
}
