// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOLensDistortionMixerBehaviour : PlayableBehaviour
{
    float m_DefaultIntensity;
    float m_DefaultXMultiplier;
    float m_DefaultYMultiplier;
    Vector2 m_DefaultCenter;
    float m_DefaultScale;

    LensDistortion m_TrackBinding;
    bool m_FirstFrameHappened;

    public override void ProcessFrame(Playable playable, FrameData info, object playerData)
    {
        ((Volume) playerData).profile.TryGet(out m_TrackBinding);
        if (m_TrackBinding == null)
            return;
        
        if(!m_FirstFrameHappened)
        {
            m_DefaultIntensity = m_TrackBinding.intensity.value;
            m_DefaultXMultiplier = m_TrackBinding.xMultiplier.value;
            m_DefaultYMultiplier = m_TrackBinding.yMultiplier.value;
            m_DefaultCenter = m_TrackBinding.center.value;
            m_DefaultScale = m_TrackBinding.scale.value;

            m_FirstFrameHappened = true;
        }


        int inputCount = playable.GetInputCount();
        float blendedIntensity = 0f;
        float blendedXMultiplier = 0f;
        float blendedYMultiplier = 0f;
        Vector2 blendedCenter = Vector2.zero;
        float blendedScale = 0f;

        float totalWeight = 0f;
        float greatestWeight = 0f;
        int currentInputs = 0;

        for(int i = 0; i < inputCount; i++)
        {
            float inputWeight = playable.GetInputWeight(i);
            ScriptPlayable<MAOLensDistortionBehaviour> inputPlayable =(ScriptPlayable<MAOLensDistortionBehaviour>)playable.GetInput(i);
            MAOLensDistortionBehaviour input = inputPlayable.GetBehaviour();
            
            blendedIntensity += input.Intensity * inputWeight;
            blendedXMultiplier += input.XMultiplier * inputWeight;
            blendedYMultiplier += input.YMultiplier * inputWeight;
            blendedCenter += input.Center * inputWeight;
            blendedScale += input.Scale * inputWeight;

            totalWeight += inputWeight;

            if (inputWeight > greatestWeight)
            {
                greatestWeight = inputWeight;
            }

            if (!Mathf.Approximately (inputWeight, 0f))
                currentInputs++;
        }
        m_TrackBinding.intensity.value = blendedIntensity + m_DefaultIntensity * (1f-totalWeight);
        m_TrackBinding.xMultiplier.value = blendedXMultiplier + m_DefaultXMultiplier * (1f-totalWeight);
        m_TrackBinding.yMultiplier.value = blendedYMultiplier + m_DefaultYMultiplier * (1f-totalWeight);
        m_TrackBinding.center.value = blendedCenter + m_DefaultCenter * (1f-totalWeight);
        m_TrackBinding.scale.value = blendedScale + m_DefaultScale * (1f-totalWeight);

    }



    public override void OnPlayableDestroy (Playable playable)
    {
        m_FirstFrameHappened = false;

        if(m_TrackBinding == null)
            return;

        m_TrackBinding.intensity.value = m_DefaultIntensity;
        m_TrackBinding.xMultiplier.value = m_DefaultXMultiplier;
        m_TrackBinding.yMultiplier.value = m_DefaultYMultiplier;
        m_TrackBinding.center.value = m_DefaultCenter;
        m_TrackBinding.scale.value = m_DefaultScale;

    }
}
