// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[Serializable]
public class MAOLensDistortionClip : PlayableAsset, ITimelineClipAsset
{
    [Range(-1f,1f)]public float intensity = 0f;
    [Range(0f,1f)]public float xMultiplier = 1f;
    [Range(0f,1f)]public float yMultiplier = 1f;
    public Vector2 center = new Vector2(0.5f, 0.5f);
    [Range(0.01f,5f)]public float scale = 1f;


    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOLensDistortionBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.Intensity = intensity;
        behaviour.XMultiplier = xMultiplier;
        behaviour.YMultiplier = yMultiplier;
        behaviour.Center = center;
        behaviour.Scale = scale;


        return playable;
    }
}
