// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOLensDistortionBehaviour : PlayableBehaviour
{
    public float Intensity;
    public float XMultiplier;
    public float YMultiplier;
    public Vector2 Center;
    public float Scale;

}
