// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOColorAdjustmentsBehaviour : PlayableBehaviour
{
    public float PostExposure;
    public float Contrast;
    public Color ColorFilter;
    public float HueShift;
    public float Saturation;

}
