// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[Serializable]
public class MAOColorAdjustmentsClip : PlayableAsset, ITimelineClipAsset
{
    public float postExposure = 0f;
    [Range(-100f, 100f)] public float contrast = 0f;
    [ColorUsage(false, true)] public Color colorFilter = new Color(1f, 1f, 1f, 1f);
    [Range(-180f, 180f)] public float hueShift = 0f;
    [Range(-100f, 100f)] public float saturation = 0f;


    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOColorAdjustmentsBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.PostExposure = postExposure;
        behaviour.Contrast = contrast;
        behaviour.ColorFilter = colorFilter;
        behaviour.HueShift = hueShift;
        behaviour.Saturation = saturation;


        return playable;
    }
}