// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOVignetteBehaviour : PlayableBehaviour
{
    public Color Color;
    public Vector2 Center;
    public float Intensity;
    public float Smoothness;
    public bool Rounded;

}
