// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[Serializable]
public class MAOSplitTonineClip : PlayableAsset, ITimelineClipAsset
{
    public Color shadows = new Color(0f, 0f, 0f, 1f);
    public Color highlights = new Color(1f, 0f, 0f, 1f);
    [Range(-100f, 100f)] public float balance = 100f;


    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOSplitTonineBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.Shadows = shadows;
        behaviour.Highlights = highlights;
        behaviour.Balance = balance;


        return playable;
    }
}