// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOPaniniProjectionMixerBehaviour : PlayableBehaviour
{
    float m_DefaultDistance;
    float m_DefaultCropToFit;

    PaniniProjection m_TrackBinding;
    bool m_FirstFrameHappened;

    public override void ProcessFrame(Playable playable, FrameData info, object playerData)
    {
        ((Volume) playerData).profile.TryGet(out m_TrackBinding);
        if (m_TrackBinding == null)
            return;
        
        if(!m_FirstFrameHappened)
        {
            m_DefaultDistance = m_TrackBinding.distance.value;
            m_DefaultCropToFit = m_TrackBinding.cropToFit.value;

            m_FirstFrameHappened = true;
        }


        int inputCount = playable.GetInputCount();
        float blendedDistance = 0f;
        float blendedCropToFit = 0f;

        float totalWeight = 0f;
        float greatestWeight = 0f;
        int currentInputs = 0;

        for(int i = 0; i < inputCount; i++)
        {
            float inputWeight = playable.GetInputWeight(i);
            ScriptPlayable<MAOPaniniProjectionBehaviour> inputPlayable =(ScriptPlayable<MAOPaniniProjectionBehaviour>)playable.GetInput(i);
            MAOPaniniProjectionBehaviour input = inputPlayable.GetBehaviour();
            
            blendedDistance += input.Distance * inputWeight;
            blendedCropToFit += input.CropToFit * inputWeight;

            totalWeight += inputWeight;

            if (inputWeight > greatestWeight)
            {
                greatestWeight = inputWeight;
            }

            if (!Mathf.Approximately (inputWeight, 0f))
                currentInputs++;
        }
        m_TrackBinding.distance.value = blendedDistance + m_DefaultDistance * (1f-totalWeight);
        m_TrackBinding.cropToFit.value = blendedCropToFit + m_DefaultCropToFit * (1f-totalWeight);

    }



    public override void OnPlayableDestroy (Playable playable)
    {
        m_FirstFrameHappened = false;

        if(m_TrackBinding == null)
            return;

        m_TrackBinding.distance.value = m_DefaultDistance;
        m_TrackBinding.cropToFit.value = m_DefaultCropToFit;

    }
}
