// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[Serializable]
public class MAOPaniniProjectionClip : PlayableAsset, ITimelineClipAsset
{
    [Range(0f, 1f)] public float distance = 0f;
    [Range(0f, 1f)] public float cropToFit = 1f;


    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOPaniniProjectionBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.Distance = distance;
        behaviour.CropToFit = cropToFit;


        return playable;
    }
}
