// This code is automatically generated by PostProcessing Extension Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
[Serializable]
public class MAOBloomClip : PlayableAsset, ITimelineClipAsset
{
    public float threshold = 0.12f;
    public float intensity = 0f;
    public float scatter = 0.443f;
    public float clamp = 65472f;
    public Color tint = new Color(0f, 0f, 0f, 1f);
    public bool highQualityFiltering = false;
    public int skipIterations = 1;
    public Texture dirtTexture;
    public float dirtIntensity = 0f;

    
    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOBloomBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.Threshold = threshold;
        behaviour.Intensity = intensity;
        behaviour.Scatter = scatter;
        behaviour.Clamp = clamp;
        behaviour.Tint = tint;
        behaviour.HighQualityFiltering = highQualityFiltering;
        behaviour.SkipIterations = skipIterations;
        behaviour.DirtTexture = dirtTexture;
        behaviour.DirtIntensity = dirtIntensity;

        
        return playable;
    }
}
