// This code is automatically generated by PostProcessing Extension Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOBloomBehaviour : PlayableBehaviour
{
    public float Threshold;
    public float Intensity;
    public float Scatter;
    public float Clamp;
    public Color Tint;
    public bool HighQualityFiltering;
    public int SkipIterations;
    public Texture DirtTexture;
    public float DirtIntensity;

}
