// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    [Serializable]
    public class MAODepthOfFieldGaussianClip : PlayableAsset, ITimelineClipAsset
    {
        public float gaussianStart;
        public float gaussianEnd;
        public float gaussianMaxRadius;
        public bool highQualitySampling;


        public ClipCaps clipCaps
        {
            get { return ClipCaps.Blending; }
        }

        public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
        {
            var playable = ScriptPlayable<MAODepthOfFieldGaussianBehaviour>.Create(graph);
            var behaviour = playable.GetBehaviour();

            behaviour.GaussianStart = gaussianStart;
            behaviour.GaussianEnd = gaussianEnd;
            behaviour.GaussianMaxRadius = gaussianMaxRadius;
            behaviour.HighQualitySampling = highQualitySampling;


            return playable;
        }
    }
}
