// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    public class MAODepthOfFieldGaussianBehaviour : PlayableBehaviour
    {
        public float GaussianStart;
        public float GaussianEnd;
        public float GaussianMaxRadius;
        public bool HighQualitySampling;

    }
}
