// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    public class MAOChannelMixerBehaviour : PlayableBehaviour
    {
        public float RedOutRedIn;
        public float RedOutGreenIn;
        public float RedOutBlueIn;
        public float GreenOutRedIn;
        public float GreenOutGreenIn;
        public float GreenOutBlueIn;
        public float BlueOutRedIn;
        public float BlueOutGreenIn;
        public float BlueOutBlueIn;

    }
}
