// This code is automatically generated by PostProcessing Extension Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
[Serializable]
public class MAODepthOfFieldBokehClip : PlayableAsset, ITimelineClipAsset
{
    public float focusDistance = 0.1f;
    public float aperture = 5.6f;
    public float focalLength = 5.6f;
    public int bladeCount = 5;
    public float bladeCurvature = 1f;
    public float bladeRotation = 0f;

    
    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAODepthOfFieldBokehBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.FocusDistance = focusDistance;
        behaviour.Aperture = aperture;
        behaviour.FocalLength = focalLength;
        behaviour.BladeCount = bladeCount;
        behaviour.BladeCurvature = bladeCurvature;
        behaviour.BladeRotation = bladeRotation;

        
        return playable;
    }
}
