// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    [Serializable]
    public class MAODepthOfFieldBokehClip : PlayableAsset, ITimelineClipAsset
    {
        public float focusDistance;
        public float aperture;
        public float focalLength;
        public int bladeCount;
        public float bladeCurvature;
        public float bladeRotation;


        public ClipCaps clipCaps
        {
            get { return ClipCaps.Blending; }
        }

        public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
        {
            var playable = ScriptPlayable<MAODepthOfFieldBokehBehaviour>.Create(graph);
            var behaviour = playable.GetBehaviour();

            behaviour.FocusDistance = focusDistance;
            behaviour.Aperture = aperture;
            behaviour.FocalLength = focalLength;
            behaviour.BladeCount = bladeCount;
            behaviour.BladeCurvature = bladeCurvature;
            behaviour.BladeRotation = bladeRotation;


            return playable;
        }
    }
}
