// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;


namespace MAOTimelineExtension.VolumeExtensions
{
    public class MAODepthOfFieldBokehBehaviour : PlayableBehaviour
    {
        public float FocusDistance;
        public float Aperture;
        public float FocalLength;
        public int BladeCount;
        public float BladeCurvature;
        public float BladeRotation;

    }
}
